### ISSUE TITLE
Typo error in top.sls

### ISSUE THREAD

**Issue by john-mathew-itt** [weslambert/securityonion-velociraptor#10]
Hi Wes,

There seems to be a typo error in top.sls file in line number 362 '- veloiraptor'. Please do check.

Regards,
John.

**Comment by weslambert** [comment]
Fixed for the `managersearch` portion. Thanks!
https://github.com/weslambert/securityonion-velociraptor/commit/9e65a18050c95439a00eed85cb8ea0ec1976b629
