### ISSUE TITLE
Velociraptor Update

### ISSUE THREAD

**Issue by john-mathew-itt** [weslambert/securityonion-velociraptor#12]
Hi,

Will there be an updated version of velociraptor docker image released or is this project abandoned?

Regards,
John Mathew.

**Comment by weslambert** [comment]
Hi @john-mathew-itt, I plan on updating the Docker image very soon. I have not abandoned this project, but have not much time to update it recently.

**Comment by john-mathew-itt** [comment]
Thanks for the prompt reply @weslambert. I really appreciate the work you do for the community!

**Comment by weslambert** [comment]
The Docker image should now be the latest release version.
