### ISSUE TITLE
Update velociraptor to latest version

### ISSUE THREAD

**Issue by john-mathew-itt** [weslambert/securityonion-velociraptor#13]
Hi Wes,

We use this image of velociraptor in our Security Onion instance and it has been a huge value add in our Incident Response efforts but we are missing out on the latest and greatest features that velociraptor provides. Really appreciate it if you can update the image.

Regards,
John M.

**Comment by weslambert** [comment]
I just pushed a new image that should include 0.7.0. Please let me know if you have any issues.

**Comment by jhnmthw** [comment]
Thanks @weslambert, this is working and no issues so far.

**Comment by john-mathew-itt** [comment]
Thanks @weslambert this is working and no issues so far.
