### ISSUE TITLE
Security onion keep all the services in wait-start after installing securityonion-velociraptor

### ISSUE THREAD

**Issue by marianoka** [weslambert/securityonion-velociraptor#2]
I have installed securityonion-velociraptor as wes says, but after rebooting the VM so does not starts. I have do manually, starting each service running so comand, it's works. 
Any Idea?

**Comment by weslambert** [comment]
Hi @marianoka, 

This is because the top file for Salt needed to be updated.  

Please place the following file in `/opt/so/saltstack/local/salt/top.sls`:

https://raw.githubusercontent.com/weslambert/securityonion-velociraptor/main/salt/top.sls
