### ISSUE TITLE
Error when trying to upgrade to SO 2.3.70

### ISSUE THREAD

**Issue by Xboarder56** [weslambert/securityonion-velociraptor#6]
Got the below error in SOUP when trying to update. I believe everything is fine based on it just being a pruning error. 

Velociraptor seems to have persisted through the upgrade as well without issues. 

----------
          ID: prune_images
    Function: cmd.run
        Name: so-docker-prune
      Result: False
     Comment: Command "so-docker-prune" run
     Started: 20:42:09.339578
    Duration: 242.978 ms
     Changes:
              ----------
              pid:
                  84523
              retcode:
                  1
              stderr:
                  so-velociraptor: Invalid version: 'testing'
              stdout:
                  Pruning old containers
----------

**Comment by marianoka** [comment]
happens the same to me
![imagen](https://user-images.githubusercontent.com/9213379/130790719-a4333b88-1083-4c5e-af41-c8c6c7c279d1.png)

**Comment by weslambert** [comment]
I think this is really just related to the version (ex. .61, ,70, etc) that the prune script is looking for, and can be ignored, unless there are any other issues.

**Comment by marianoka** [comment]
Hi wes! 
In fact I have ignored the error. Evth seems to works fine.
I'll let you know

**Comment by weslambert** [comment]
Okay, closing for now -- I don't think there is anything we can do, outside of changing the Docker prune script, and that is native to Security Onion, so I'd rather not.
