### ISSUE TITLE
Not able to add any clients to Velociraptor

### ISSUE THREAD

**Issue by ghost** [weslambert/securityonion-velociraptor#9]
Hi Wes, 
I am not able to add any clients to Velociraptor. I am stuck at this Info and getting timed out.
[INFO] 2022-07-13T12:24:03+05:30 While getting https://192.168.10.174:8000/: Get "https://192.168.10.174:8000/server.pem": dial tcp 192.168.10.174:8000: connect: connection timed out
I have added the hosts using so-firewall.
Anything which is missing?

**Comment by weslambert** [comment]
It sounds like a firewall issue. Let me see if I can reproduce with the steps provided in the README, and I'll get back with you.

**Comment by ghost** [comment]
Figured out the issue Wes. It was a firewall issue. The thing is, so-firewall changes made for velociraptor was not added in  /opt/so/saltstack/local/pillar/minions/<HOSTNAME>_<ROLE>.sls in the managersearch node in my case.
